name: Build documentation

on:
    push:
        branches:
            - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow one concurrent deployment
concurrency:
    group: "pages"
    cancel-in-progress: true

# Default to bash
defaults:
    run:
        shell: bash

env:
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5
              with:
                  fetch-depth: 0
            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.12"
            - name: Setup Graphviz
              uses: ts-graphviz/setup-graphviz@v2
            - name: Serve Ollama Model
              uses: phil65/ollama-github-action@v1
              with:
                  model: "smollm2:360m"
            - name: Install uv
              uses: yezz123/setup-uv@v4
            - name: Install dependencies
              run: |
                  uv sync --all-extras
            - name: Build
              run: uv run mknodes build -v
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v4
              with:
                  path: ./site

    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
